@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User")
Container(loadBalancer, "Load Balancer", "Nginx", "Uses round robin")
Container(apiGateWay,"API GateWay")

ContainerQueue(messageQueue, "Events queue", "Kafka", "Saves new posts and subscriptions")
Container(post,"Post Service","","CRUD for posts")
ContainerDb(postDB, "POST database", "PgSQL", "Stores users' posts",  $tags="db")
Container(media,"Media service","","put ant get users' media and replace media from temporary table to constant")
ContainerDb(mediaDB, "Media database", "S3 Minio", "Stores users' media",  $tags="db")
Container(subscription,"Subscription service","","CRUD for subscriptions users to each other")
ContainerDb(subscriptionDB, "Subscription database", "PgSQL", "save info about users' subscriptions to other users",  $tags="db")
Container(place,"Place service","","Search info about places")
ContainerDb(placeDB, "Place database", "PgSQL", "Stores info about places",  $tags="db")
Container(cdc,"CDC","Debezium","Controls for changes in POST DB and sync media files with Media DB")
Container(feed,"Feed Service", "","prepare users' feeds")
ContainerDb(feedDB, "Feed database", "Redis", "Stores users feeds",  $tags="db")

Rel(user,loadBalancer,"REST")
Rel(loadBalancer,apiGateWay,"REST")
Rel(apiGateWay,post,"REST")
Rel(post,postDB,"put and get posts","REST")
Rel(apiGateWay,media,"REST")
Rel(media,mediaDB,"put and get media","REST")
Rel(apiGateWay,subscription,"REST")
Rel(subscription,subscriptionDB,"put and get info about subscriptions","REST")
Rel(apiGateWay,feed,"get user's feed","REST")

Rel(apiGateWay,place,"request of searching place","REST")
Rel(place,placeDB,"get info about places","REST")
Rel(cdc,postDB,"get changes of url_media","REST")
Rel(cdc,media,"sends info about new url media in posts DB","REST")
Rel(feed,feedDB,"prepare and get feeds","REST")
Rel(feed,subscription,"Get actual list of user's subscriptions","REST")


Rel(post, messageQueue, "Publishes new post","REST")
Rel(subscription, messageQueue, "Publishes new subscriptions","REST")
Rel(feed,messageQueue, "get new posts and subscriptions")

@enduml